### ISSUE TITLE
ResizeObservers might be incompatible with interruptible reflow

### ISSUE THREAD

**Issue by dholbert** [WICG/ResizeObserver#17]
Firefox has a feature called "Interruptible Reflow" (originally implemented in [bug 67752](https://bugzilla.mozilla.org/show_bug.cgi?id=67752)) which allows us interrupt long-running layout tasks at specific defined times to allow for repaint & user-interaction, and then resume layout shortly thereafter.  (Right now, we only interrupt if (a) the layout has taken more than 100ms, and (b) there are pending user input events, e.g. the user has tried to click a link or perform some other action.)

I fear that this "Interruptible Reflow" feature might be fundamentally incompatible with ResizeObserver. In particular, the ResizeObserver strongly assumes that an callback-triggered 2nd-pass of layout will run to completion (before painting), so that the user never sees an intermediate state.  (The spec might implicitly assume that each "main" pass of layout runs to completion, too, though I'm not as sure about that.)

Right now, to make Firefox match the ResizeObserver spec, we'd simply have to disable interruptible reflow in pages that have ResizeObservers registered.  That's not difficult, but I'm curious if we can instead broaden the ResizeObserver spec instead to accommodate/allow for these sorts of interruptions.  It seems unfortunate to lose this useful responsiveness win.

I don't have any specific suggestions yet, but I just wanted to start this discussion somewhere (& see if you'd run up against anything like this as well in Chrome) -- hence, filing this issue.

**Comment by atotic** [comment]
Very interesting. I am also starting some event-loop related work, and have been investigating how different browsers implement it. https://github.com/atotic/event-loop. We'd like to harmonize what different browsers do.

Regarding "interruptible reflow": I have to think through what all the implications of interruptible reflow are, not  just on ResizeObserver, but on the entire event loop. I do not think that this is part of the spec.

My initial feel is that ResizeObserver and interruptible reflow can coexist. The page should not have worse behavior just because RO has been created.

What layout does FF paint if reflow is interrupted? The initial layout, or the partially completed layout?

My initial idea is that if layout is interrupted, FF should  stop resize notifications, and deliver them in the next 'good' rAF cycle instead. This might show up as an incorrectly painted single frame. This might not be too bad since layout taking longer than 100ms might be causing some strange painting anyway.

Hard to tell what the right thing to do is without knowing when this happens in real world today, and what the performance implications are. Do you have any suggestions?

I am also curious about how does interruptible layout interacts with the event-loop. What events are fired, etc....

**Comment by dholbert** [comment]
> What layout does FF paint if reflow is interrupted? The initial layout, or the partially completed layout?

The partially completed layout.

> My initial idea is that if layout is interrupted, FF should stop resize notifications, and deliver them in the next 'good' rAF cycle instead. This might show up as an incorrectly painted single frame. This might not be too bad since layout taking longer than 100ms might be causing some strange painting anyway.

That sounds reasonable. I don't have any suggestions that are better than this, I think.

> I am also curious about how does interruptible layout interacts with the event-loop. What events are fired, etc....

After an interruption, it looks like we register to be notified on the next tick of the "refresh driver" (our ~60hz throttler class), and we retry the layout when that fires, and the event loop runs in the meantime.  So, events can be fired & script can run between a layout being interrupted & the layout resuming.  (Note also that not all types of reflow are interruptible -- e.g. if script asks for geometry information like `offsetTop` and we need to flush layout to return a value, then that won't be interrupted.)

**Comment by atotic** [comment]
@dholbert any news on FF? My chrome changes have just landed today, and I've updated the tests in this repo.

**Comment by dholbert** [comment]
@fariskhi's working on it -- hopefully we'll have an implementation posted soon over at [bug 1272409](https://bugzilla.mozilla.org/show_bug.cgi?id=1272409). (You can follow along there if you like.)

Great to hear that it's landed in Chrome!
