### ISSUE TITLE
Need Clarification: Deliver Skipped Observations in Next Cycle

### ISSUE THREAD

**Issue by ghost** [WICG/ResizeObserver#22]
Currently the final step of ResizeObserver notifcations in the spec is

> If Document has skipped observations then deliver resize loop error notification

The spec does not mention anything about 'the fate' of skipped observations.

In test0 of https://github.com/WICG/ResizeObserver/blob/master/test/eventloop.html, when resize loop happens, we deliver all pending notifications without skipped observations until we don't have any active observations. And then, all skipped observations from before get notified (t1 and t2). If we don't notify t1 and t2, the test failed.

Currently in our patches for ResizeObserver in Firefox, to pass the test case, we just schedule another notification so all skipped observations will be delivered in next cycle after layout. In Chromium, I think it also call schedule animation after delivering ErrorEvent for resize loop.

We need to define the expected behavior for this in the spec.

Also, is this an expected behavior? http://jsbin.com/jawedeqedi/1/edit?html,js,console,output

It is a simple case and will cause infinite loop in Chromium with ResizeObserver enabled (and Firefox with our patches applied). Basically because we always deliver skipped observations after ErrorEvent for resize loop delivered.

**Comment by atotic** [comment]
> The spec does not mention anything about 'the fate' of skipped observations.

Yes, the fate is implied, but not spelled out. This is because the specified algorithms do not explicitly keep keep track of skipped observations. The following rules decide their fate:
- ResizeObservation keeps track of the size of the last notification. 
- At the start of each event loop, all ResizeObservations whose size differs from Element's size generate a notification.
- So, implicitly, any observations that do not fire, will be eligible to fire in the next loop. And they will, except for edge case where developer sets their size back to match what ResizeObservation holds.

I'll add an explanatory note to the spec.

> Also, is this an expected behavior? http://jsbin.com/jawedeqedi/1/edit?html,js,console,output

Yes. 
- an error is generated because there are skipped observations
- it is not an infinite loop in ResizeObserver, it is an infinite loop created by the developer. User interface is not hung. Just like writing:
  
  ```
  function infiniteLoop() { 
    console.log("hi");
    window.setTimeout(infiniteLoop, 0);
  }
  window.setTimeout(infiniteLoop, 0);
  ```

is not a true infinite loop.
