### ISSUE TITLE
Should contentRect values be CSSUnitValues?

### ISSUE THREAD

**Issue by eeeps** [WICG/ResizeObserver#41]
Seems like APIs of the future should use [CSSUnitValues](https://drafts.css-houdini.org/css-typed-om/#simple-numeric), instead of numbers, when dealing with lengths.

`CSSUnitValue {value: 100, unit: "px", type: "length"}` > `100` because:

- it's more accurate and understandable
- converting and comparing it to other units/values is simpler and more robust

**Comment by atotic** [comment]
I do not have deep knowledge of CSSOM, so I talked to Tab to better understand pros and cons, and did some spec reading. I am strongly leaning towards just using numbers. 

The difference between using numbers vs CSSUnitValues is small. Conversion between the two is trivial.

    // cssom => double
    doubleValue = contentRect.width.to("px").value
    // double => cssom
    cssomValue = CSS.px(contentRect.width)

The reason for strongly leaning towards keeping doubles is consistency with the rest of current DOM APIs. Most of the code written today uses numbers.

contentRect values are derived from CSS, but come from DOM. They are physical pixel locations.

> it's more accurate

Since contentRect values will always be pixel units, the accuracy is the same. CSSUnitValue also uses double to represent value.

> it's more understandable

Only if you are familiar with CSSOM.

> converting and comparing it to other units/values is simpler and more robust

True. But, as shown in code above, conversion is trivial.

**Comment by eeeps** [comment]
Thanks for researching and considering. I agree, “accurate” is a bit of a misnomer, conversion is easy, and it’ll only be more predictable/understandable if it’s consistent with other APIs. I totally get that right now it’s more important to be consistent with existing APIs (and provide non-Chrome browsers a lower-barrier-to-implementation) than it is to trail-blaze the CSSOM and (maybe? probably?) be consistent with APIs of the future.

**Comment by tabatkins** [comment]
More generally, I think that we shouldn't return CSSUnitValues from most DOM APIs; they're virtually all px already, and rarely need to mix with non-px values. The mixing is the big win from Typed OM; if you want to add 20px to some length, you don't need to worry about if the current value is specified in px or em or whatever, you just `.add(CSS.px(20))` and call it a day. That's not directly relevant to DOM APIs; the value is always in px already.
