### ISSUE TITLE
This should probably just be an event?

### ISSUE THREAD

**Issue by domenic** [WICG/ResizeObserver#43]
Per the discussion in https://github.com/w3ctag/design-principles/issues/78 , it seems like the reasons for making this an XObserver may not have been well-motivated. (Vague performance concerns with no measurements.)

I tried to write up all the possible reasons you might use an XObserver instead of an event at https://github.com/w3ctag/design-principles/pull/79, but ResizeObserver doesn't seem to take advantage of almost any of them:

- It doesn't take any options to allow customizing each observation
- It doesn't take any creation-time options which would be useful to reuse on multiple targets
- It doesn't even have a takeRecords() method, so presumably the deliver-records-now use case is not important for users of ResizeObserver
- Since it already has a natural target (elements), the not-having-to-type-an-event-type advantage is moot.

It does have a disconnect() method, but I don't see any examples in the spec of people using that to stop observing many elements at once, so I'm unsure whether having that is so important that we need to depart from the EventTarget pattern.

If this was an event, it would simply be

```js
element.addEventListener("resize", e => {
  for (const entry of e.entries) {
    // ...
  }
});
```

and then it would work with all the many frameworks that interoperate well with events today.

Note that as an event, the timing, delivery, and batching processing model would stay exactly the same. It would only be the surface API that changes.

WDYT?

**Comment by atotic** [comment]
My current understanding is that in the future, we might want to add arguments to "observe".

@bfgeek and @ojanvafai were the champs of the observer pattern. Where any other reasons for the "observer" pattern?

**Comment by jakearchibald** [comment]
Is the performance worry down to event bubbling? I guess it doesn't have to bubble.

**Comment by bfgeek** [comment]
The primary reason is that we can add additional arguments in the future - this is a very minimal mvp. E.g. this doesn't give you individual fragment information. For example if the web developer wanted to know the size of individual text fragments.

```js
const ro = new ResizeObserver((entries) => {
  /* instead of client box size, you'd have all child fragment information */
  entries[0].clientRects; // or something.
 });
ro.observe(span, { clientRects: true });
```

Additional layout information like client rects is relatively expensive to calculate, and needs to be calculated up-front to keep the performance characteristics of RO.

There have been asks for having `takeRecords()` (I.e. flush layout) be we are unsure yet how to do this well, as this would conceptually muck around with ordering.

**Comment by domenic** [comment]
@bfgeek do you really anticipate it being useful to observe multiple targets with different options? Your example doesn't make sense from that perspective since your callback assumes clientRects exists, but you could call observe() multiple times, sometimes with clientRects: true, sometimes with it false.

**Comment by ojanvafai** [comment]
On the performance side, bubbling doesn't have an impact. The primary cost is the O(n) work of computing the ancestor chain, which you have to do upfront for capturing. So, I think the performance argument does actually apply here. I commented the same here: https://github.com/w3ctag/design-principles/issues/78#issuecomment-335248762

On the ergonomics side:
 - The observer pattern makes it more clear that this is async with respect to the layout. I realize events can be async too, so that's not a definitive argument in either direction.
 - I think it's more natural to batch with the observer pattern than with the event pattern. With events you'd typically have one event per resize, but that's inefficient in cases where you had multiple layouts. So, the batching would need to have all the useful information in an "entries" field on the event.

@domenic MutationObserver handles configuration options that get different values in the entries objects fine (like in @bfgeek's example), right?

**Comment by domenic** [comment]
I don't think either of those ergonomics arguments holds very well. Events can be at any timing (and are, all over the platform); and events can contain batched data just as easily. An entries field is a very natural field for an event to have.

In return, you sacrifice the significant ergonomic benefits of events, e.g. being able to use third party libraries like jQuery, RxJS, or React/Angular/etc.'s event-binding syntax.

MutationObserver does handle it, but @bfgeek's example does not. It will give undefined when the configuration is not true, probably leading to errors when you try to iterate over clientRects. So while this pattern may work for MutationObserver, it doesn't work well for clientRects/ResizeObserver.

**Comment by ojanvafai** [comment]
From the discussion on w3ctag/design-principles#78 it sounds like there's an alternate solution that addresses the differences from events without taking on the performance overhead of events on Nodes or losing the ability to configure observations later.

```
 +    const observer = new ResizeObserver(element, { root, rootMargin, threshold });
 +
 +    function listener(e) {
 +        for (const change of e.changes) { ... }
 +    }
 +
 +    observer.addEventListener("resize", listener);
 +    observer.removeEventListener("resize", listener);
```
Eventually, we can add an EventListenerOptions subclass as the third argument to addEventListener for ResizeObservers that allows configuring in individual event listeners if needed.

And if we add disconnect() and deliverPending to EventTarget (or maybe a subclass of EventTarget), then we don't lose anything from not using observer pattern aside from the redundant event name.

**Comment by atotic** [comment]
Thanks for an elucidating discussion. I've learned that performance is no longer an issue. Now we have 3 options:

1) Observer pattern: ResizeObserver as currently designed

    (1.1-) not an EventTarget, cannot take advantage of event APIs.
    (1.4-) already implemented, spec'd
    (1.2+) future expansion: additonal options to observe() ( ex: clientRects)
    (1.3+) future expansion: additional fields to reported entry.

2) node is EventTarget + resize event : node.addEventListener("resize",....)

    (2.1-) no future expansion: no way to add additional options to observe, and no way to add new fields to result.
    (2.2+) EventTarget, can use standard ways of handling events.

3) Hybrid: ResizeObserver as a stand-alone EventTarget (ojan's example)

    I fail to see the appeal of this approach. A new EventTarget is created for every Node to be observed. 
    This is done so we can simulate passing additional arguments to addEventListener, and call takeRecords? 
    As a webdev, I'd prefer extending the existing `Node.addEventListener()` framework and reuse this pattern when needed.
```javascript
    Node.addEventListener("resize", handler, { ...,  eventSpecificOptions: {});
    Node.dispatchPendingEvents("resize");  // alternative to "takeRecords()"
```

So, what do we do?

Personally, I've  had a preference to model Element.resize after window.resize for simplicity reasons. I've  found Observer pattern unusual, and awkward:
- batching notifications to a single callback meant that I have to hand-code notification routing to appropriate nodes. 
- cannot use it with event utilities, no onresize=""

When I examined existing uses of ResizeObserver, most of the usage was one ResizeObserver per observed Node, which is how one would use EventTarget.

I am still unclear about what the long term plans are for an extensible EventTarget. Will events be extended to allow adding "custom options" to addEventListener?

If the answer is "no", I think Observer is the right choice.
If the answer is "yes", then the right choice for webdev is EventTarget. This also means rewriting the spec, code, etc. Lots of duplicated work....

**Comment by domenic** [comment]
I'm still trying to assemble my thoughts on configurability and stand-alone event targets, per @atotic's last comment, but I want to get more info on this concern:

> performance overhead of events on Nodes

At present this argument doesn't seem compelling to me. No measurements have been provided showing it to be a real-world problem for how people observe resizes. (E.g., how many milliseconds of jank would it add, for an event that fires, IIUC, at most every animation frame?). And even if they were shown to be significantly slower, I'd want some strong assurances that it wasn't Chrome-specific. Would it be fruitful to redirect some of this engineering effort we're putting into coming up with novel designs into instead improving the performance of event dispatch? For example, if there are no capture listeners for the "resize" event, it sounds like the expensive-in-Chrome path computation could be skipped.

One way to make the discussion clearer is, if we could wave a magic wand and make `node.addEventListener("resize", ...)` as fast as `ResizeObserver` in Chrome, would we still be interested in using `ResizeObserver`? I'd be very interested in people's answer to this question.

**Comment by tabatkins** [comment]
> no way to add additional options to observe, and no way to add new fields to result.

You can definitely add new fields to the result whenever you want; the event object is just an object, controlled by your spec, so it can sprout new properties whenever you want.

But passing additional options to observe is a stickler. @domenic, I think this is the big issue here.  This is a bad API point for the approaches to diverge on; it means that if we start by assuming we don't need any custom options (and thus use events) we can't later add options; if we think we might need custom options in the future (and thus use an observer) we might not never end up adding them and pay for the complexity forever.

But right now, it looks like `AddEventListenerOptions` is a centrally-controlled dictionary. Is it acceptable to add new fields to it via `partial` that are used only for particular events?  This means we have to manage a global namespace over time.  Alternately, could `aEL()` loosen the typing on its `options` argument, such that particular `type` arguments can parse the `options` as different dictionaries? (That way different events can use the same option name, even with different types.)

(I think this has been brought up before as an "open" or "half-open" dictionary? I think the IDL would be that `options` becomes just an `object`, and then specs define their own dictionaries and [convert](https://heycam.github.io/webidl/#es-dictionary) the object into the desired type. DOM then says (a) all such types must subclass `AddEventListenerOptions`, and (b) unless specified otherwise for a particular event, by default the object is converted to an `AddEventListenerOptions` value.)

**Comment by determin1st** [comment]
i agree. make it simpler. make it a function.
